<?php

return array (
  0 => 
  array (
    0 => 'red',
    1 => 'green',
    2 => 'blue',
    3 => 'magenta',
    4 => 'yellow',
    5 => 'chocolate',
    6 => 'black',
    7 => 'aquamarine',
    8 => 'lime',
    9 => 'fuchsia',
    10 => '#b0a00',
    11 => 'azure',
    12 => 'brown',
    13 => '#b0000e',
    14 => 'deeppink',
  ),
  1 => 
  array (
    0 => 'aliceblue',
    1 => 'gray',
    2 => '#c000e0',
    3 => 'coral',
    4 => '#fed0a0',
    5 => 'orange',
    6 => 'orchid',
    7 => 'pink',
    8 => 'plum',
    9 => '#00a000',
    10 => 'purple',
    11 => 'aliceblue',
    12 => '#a00000',
    13 => 'blanchedalmond',
    14 => 'blueviolet',
  ),
  2 => 
  array (
    0 => 'beige',
    1 => 'burlywood',
    2 => 'bisque',
    3 => 'cadetblue',
    4 => 'pink',
    5 => 'saddlebrown',
    6 => 'royalblue',
    7 => 'rosybrown',
    8 => 'purple',
    9 => '#0e0eed',
    10 => 'olivedrab',
    11 => 'powderblue',
    12 => 'peachpuff',
    13 => 'papayawhip',
    14 => 'paleturquoise',
  ),
  3 => 
  array (
    0 => 'palevioletred',
    1 => 'palegreen',
    2 => '#a0b0e0',
    3 => 'navajowhite',
    4 => '#a00d00',
    5 => '#00e0ed',
    6 => 'yellowgreen',
    7 => 'tomato',
    8 => 'turquoise',
    9 => 'thistle',
    10 => 'springgreen',
    11 => 'steelblue',
    12 => 'salmon',
    13 => '#ca0e00',
    14 => 'sienna',
  ),
  4 => 
  array (
    0 => 'silver',
    1 => 'tan',
    2 => 'thistle',
    3 => 'turquoise',
    4 => 'violet',
    5 => 'snow',
    6 => 'salmon',
    7 => '#ca0e00',
    8 => 'sienna',
    9 => 'silver',
    10 => 'tan',
    11 => 'thistle',
    12 => 'turquoise',
    13 => 'violet',
    14 => 'chartreuse',
  ),
  5 => 
  array (
    0 => 'darkslategray',
    1 => 'darkseagreen',
    2 => 'darkred',
    3 => 'mediumslateblue',
    4 => 'mediumvioletred',
    5 => 'oldlace',
    6 => '#0a0000',
    7 => 'goldenrod',
    8 => 'wheat',
    9 => 'whitesmoke',
    10 => 'orange',
    11 => 'moccasin',
    12 => 'mistyrose',
    13 => 'mintcream',
    14 => 'midnightblue',
  ),
  6 => 
  array (
    0 => 'dimgray',
    1 => 'darksalmon',
    2 => 'slategray',
    3 => 'skyblue',
    4 => 'sienna',
    5 => 'seashell',
    6 => 'salmon',
    7 => 'seagreen',
    8 => 'sandybrown',
    9 => 'firebrick',
    10 => 'gold',
    11 => 'khaki',
    12 => '#0a0000',
    13 => 'goldenrod',
    14 => 'wheat',
  ),
  7 => 
  array (
    0 => 'whitesmoke',
    1 => 'mediumturquoise',
    2 => 'navy',
    3 => 'mediumspringgreen',
    4 => 'mediumseagreen',
    5 => '#ed0000',
    6 => 'peru',
    7 => 'mediumorchid',
    8 => 'mediumblue',
    9 => 'mediumaquamarine',
    10 => 'maroon',
    11 => 'limegreen',
    12 => 'lightyellow',
    13 => 'lightsteelblue',
    14 => 'magenta',
  ),
  8 => 
  array (
    0 => '#0000b0',
    1 => 'lightslategray',
    2 => 'lightskyblue',
    3 => '#00e0',
    4 => 'lightseagreen',
    5 => 'lightsalmon',
    6 => 'lightpink',
    7 => 'plum',
    8 => '#0000a0',
    9 => 'lightgreen',
    10 => '#00dee0',
    11 => 'indianred',
    12 => 'lavender',
    13 => 'lightblue',
    14 => 'lavenderblush',
  ),
  9 => 
  array (
    0 => 'lightcoral',
    1 => 'lightcyan',
    2 => '#00ded0',
    3 => 'hotpink',
    4 => 'greenyellow',
    5 => 'lemonchiffon',
    6 => 'lawngreen',
    7 => 'darkorchid',
    8 => 'deepskyblue',
    9 => 'honeydew',
    10 => '#00e00d',
    11 => 'forestgreen',
    12 => '#00000e',
    13 => 'greenyellow',
    14 => 'gainsboro',
  ),
  10 => 
  array (
    0 => 'firebrick',
    1 => 'dodgerblue',
    2 => 'darkturquoise',
    3 => 'darkslateblue',
    4 => 'darkslategray',
    5 => 'darkseagreen',
    6 => 'darkred',
    7 => 'darkorchid',
    8 => '#da000e',
    9 => 'darkslateblue',
    10 => 'darkviolet',
    11 => 'floralwhite',
    12 => 'cyan',
    13 => 'darkgoldenrod',
    14 => 'cornsilk',
  ),
  11 => 
  array (
    0 => 'darkolivegreen',
    1 => '#b0ed00',
    2 => 'darkblue',
    3 => 'darkcyan',
    4 => 'darkgreen',
    5 => '#da0000',
    6 => 'ivory',
    7 => 'darkmagenta',
    8 => 'darkgray',
    9 => '#c000b0',
    10 => '#c000b0',
    11 => 'darkviolet',
    12 => 'floralwhite',
    13 => '#da000e',
    14 => 'darkslateblue',
  ),
  12 => 
  array (
    0 => '',
  ),
);